"""Automation metrics — measure before trusting.

Tracks:
  - Which operations are automated vs manual
  - Build completeness (all expected outputs present)
  - Health check integration (pass/fail counts)
  - Freshness (when was each output last generated)

Usage:
    python -m universe_explorer.reader.automation_metrics
"""

from __future__ import annotations

import json
import os
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

_DIST_DIR = Path(__file__).parent.parent.parent / "dist"


@dataclass
class OutputMetric:
    """Metric for one output file."""

    name: str
    path: str
    exists: bool = False
    size_bytes: int = 0
    last_modified: Optional[str] = None
    automated: bool = False  # generated by build.py

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "path": self.path,
            "exists": self.exists,
            "size_bytes": self.size_bytes,
            "last_modified": self.last_modified,
            "automated": self.automated,
        }


@dataclass
class AutomationMetrics:
    """Complete automation metrics."""

    timestamp: str = ""
    total_outputs: int = 0
    automated_outputs: int = 0
    manual_outputs: int = 0
    missing_outputs: int = 0
    health_status: str = "unknown"
    outputs: List[OutputMetric] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "timestamp": self.timestamp,
            "total_outputs": self.total_outputs,
            "automated_outputs": self.automated_outputs,
            "manual_outputs": self.manual_outputs,
            "missing_outputs": self.missing_outputs,
            "health_status": self.health_status,
            "automation_rate": f"{self.automated_outputs}/{self.total_outputs}",
            "outputs": [o.to_dict() for o in self.outputs],
        }

    @property
    def is_fully_automated(self) -> bool:
        return self.automated_outputs == self.total_outputs

    @property
    def automation_rate(self) -> str:
        return f"{self.automated_outputs}/{self.total_outputs}"

    @property
    def has_all_outputs(self) -> bool:
        return self.missing_outputs == 0


# Expected outputs with their automation status.
EXPECTED_OUTPUTS = [
    # Core pages (automated by build.py)
    ("index.html", True),
    ("app.html", True),
    ("universe.html", True),
    ("explore3d.html", True),
    ("scene3d.json", True),
    ("explore.html", True),
    ("explore-zh.html", True),
    ("claims.json", True),
    ("about.html", True),
    ("about-zh.html", True),
    ("feed.xml", True),
    ("zh.html", True),
    ("app-data.json", True),
    ("health.html", True),
    ("health.json", True),
    ("changes.html", True),
    # Phase 1-3 pages (automated by build.py)
    ("review.html", True),
    ("epistemic_map.html", True),
    ("epistemic-graph.json", True),
    ("explore-v2.html", True),
    ("challenge.html", True),
    ("dual-axis.svg", True),
    ("dashboard.html", True),
    ("stats.json", True),
    # Domain pages (automated by build.py)
    ("black_hole.html", True),
    ("cosmology.html", True),
    ("dark_matter.html", True),
    ("stars.html", True),
    ("exoplanets.html", True),
    ("planets.html", True),
    ("ocean.html", True),
    ("seismology.html", True),
    ("polar.html", True),
]


def compute_metrics() -> AutomationMetrics:
    """Compute automation metrics."""
    metrics = AutomationMetrics(
        timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    )

    for name, automated in EXPECTED_OUTPUTS:
        path = _DIST_DIR / name
        exists = path.exists()
        size = path.stat().st_size if exists else 0
        mtime = None
        if exists:
            mtime = datetime.fromtimestamp(
                path.stat().st_mtime, tz=timezone.utc
            ).strftime("%Y-%m-%dT%H:%M:%SZ")

        metric = OutputMetric(
            name=name,
            path=str(path),
            exists=exists,
            size_bytes=size,
            last_modified=mtime,
            automated=automated,
        )
        metrics.outputs.append(metric)
        metrics.total_outputs += 1
        if automated:
            metrics.automated_outputs += 1
        else:
            metrics.manual_outputs += 1
        if not exists:
            metrics.missing_outputs += 1

    # Health status.
    try:
        from ..data.registry import TOPICS
        from .health_check import run_health_checks
        checks = run_health_checks(TOPICS)
        errors = sum(1 for c in checks if c.status == "error")
        metrics.health_status = "error" if errors > 0 else "ok"
    except Exception:
        metrics.health_status = "unknown"

    return metrics


def format_metrics_report(metrics: AutomationMetrics) -> str:
    """Human-readable metrics report."""
    lines = [
        "Automation Metrics",
        "=" * 40,
        f"Timestamp: {metrics.timestamp}",
        f"Total outputs: {metrics.total_outputs}",
        f"Automated: {metrics.automated_outputs}",
        f"Manual: {metrics.manual_outputs}",
        f"Missing: {metrics.missing_outputs}",
        f"Automation rate: {metrics.automation_rate}",
        f"Health: {metrics.health_status}",
        "",
        "Outputs:",
    ]

    for o in metrics.outputs:
        status = "✓" if o.exists else "✗"
        auto = "auto" if o.automated else "manual"
        size = f"{o.size_bytes:,}B" if o.exists else "—"
        lines.append(f"  {status} {o.name:30} {auto:6} {size:>10}")

    if not metrics.has_all_outputs:
        lines.append("")
        lines.append("WARNING: Missing outputs. Run 'python build.py' first.")

    return "\n".join(lines)


if __name__ == "__main__":
    metrics = compute_metrics()
    print(format_metrics_report(metrics))

    # Write metrics to dist/.
    _DIST_DIR.mkdir(parents=True, exist_ok=True)
    out = _DIST_DIR / "automation-metrics.json"
    out.write_text(
        json.dumps(metrics.to_dict(), indent=2, ensure_ascii=False),
        encoding="utf-8")
    print(f"\nautomation-metrics.json -> {out}")
